### PR TITLE
Add an include for secret management

### PR DESCRIPTION
**Pull request by smaslennikov**
@naftulikay ready for your review

### CODE REVIEW

**Comment by naftulikay** [comment]
@smaslennikov The goal of this repository in the future is to basically reparent all the `*.mk` files to the root directory and use this as a git submodule so we are always using the same generic tooling. As such, this has implementation data in it and shouldn't be merged. I know that there's already hardcoded things in here, but the goal is to get rid of them.

I have done some testing already to show that I can support multiple cloud providers and different backends with the same code, but I need to backport that here. The goal is to have this `include.d/` of this repository which sources `terraform.mk` at the root of the repository to provide AWS account id, Google Project, bucket name, etc.

**Comment by smaslennikov** [comment]
@naftulikay understood. I amended the include to rather use an ENVVAR for recipients, with a meaningful error when not set.

**Comment by smaslennikov** [comment]
There has been a need for this in the past.

**Comment by naftulikay** [comment]
Whatever

**Comment by smaslennikov** [comment]
@naftulikay, [this](https://github.com/smaslennikov/include.mk) has more up-to-date crypto includes, maybe we should revert this PR and link there or something.

**Comment by naftulikay** [comment]
If you want to put in the README a link to yours, that would be good. I'd have to dive into the details a lot more to discover if everything makes sense from a modular point of view.

**Pull request merged**
